### ISSUE TITLE
[TRAINNING] Estudo Django Rest

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-Hora-Da-Hora#10]
### O que será estudado:

1. Introdução
2. Preparação do ambiente de desenvolvimento
3. Desenvolvendo uma API de pontos turísticos.
4. Desenvolvendo recursos avançados na API.
5. Utilizando imagens nos pontos turísticos e atrações.
6. Filtros de querysets.
7. Habilitando buscas na API.
8. Autenticação e autorização.
9. Aprofundando conhecimentos sobre serializers.
10. Trabalhando com nesteds relationships.

### Objetivo:

Elevar e nivelar os conhecimentos sobre django rest da equipe de MDS, eles iram realizar o curso "Criando poderosas API's RESTful com Django Rest Framework" na plataforma udemy, disponível em: https://www.udemy.com/apis-restful-com-django-rest-framework/

**Estimativa de Duração** : 5 horas.
**Obs:** Essa estimativa foi feita em horas de videos do curso disponibilizado.

**Comment by matheus-rn** [comment]
Os membros tiveram problemas na configuração do ambiente, então foi criado um ambiente base para que pudessem dar prosseguimento ao curso.

https://github.com/matheus-rn/curso_django

**Comment by lucasA27** [comment]
Ótimo curso para ter um conhecimento intermediário sobre Django rest. Tive algumas dificuldades na criação do ambiente, que foram solucionadas com ajuda do grupo em geral. Outra dificuldade foi nos conceitos em si, tendo em vista que, não tinha compreensão sobre o que é uma API.

**Comment by jpcirqueira** [comment]
Tive muitos problemas na configuração do ambiente do curso e problemas, porém o curso foi importante para um melhor entendimento do Framework . O curso demandou muitas horas além do esperado por conta do problema no ambiente.

**Comment by MatheusEstanislau** [comment]
Diversos problemas na criação e configuração do ambiente. Por ser um curso de nivel básico-intermediário o instrutor deveria ter focado mais na explicação das funcionalidades e não em apenas digitar comandos, o que resultou num entendimento muito superficial da ferramenta.

**Comment by MoacirMSJ** [comment]
Ótimo curso para ter uma noção básica da estrutura e recursos do Django rest.

**Comment by RCristyan** [comment]
Excelente a experiência de conhecer melhor os recursos do Django Rest através do curso, apesar de ter sido muita informação em pouco tempo, o que foi prejudicial para minha assimilação.
Acredito que quando começar a usar o Django Rest no projeto irei aprender melhor seu verdadeiro potencial

**Comment by lukassxp** [comment]
Todos os membros da equipe de MDS concluirão o curso e deixaram seu feedback sobre a atividade, portanto o objetivo do treinamento foi atingido e a issue pode ser considerada feita!
