### ISSUE TITLE
[DOC] NFR Framework

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-Hora-Da-Hora#11]
### Descrição:

Trata-se de um framework conceitual para condução da Engenharia de Requisitos orientada aos requisitos não funcionais, com uma extensão que apoia suposições para avaliação de satisfação das metas-flexíveis..

### Tópicos do documento

- [x] Introdução
- [x] NRF
- [x] Ferramenta utilizada
- [x] Referencias bibliográficas 
- [x] Histórico de revisão

### Comentários

Sugestão de ferramenta: [StarUML](http://staruml.io/) 

**Exemplos:**

- https://github.com/2018-2-Desenho/CabecaVoleiJoelhoPe/wiki/NFR
- https://github.com/QueroMais/QueroMaisConversa/wiki/NFR-Framework

**Comment by LucasSiqz** [comment]
Foi feito o NFR priorizando 4 requisitos não funcionais: Usabilidade, Portabilidade, Segurança, Desempenho. A tarefa contou com a presença ativa de um membro de MDS, pois este documento seria utilizado na parte da descrição dos requisitos não funcionais no documento de visão.

**Comment by lukassxp** [comment]
Documento revisado e está ok!

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-nfr
