### ISSUE TITLE
[US01] Prototipação 

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-Hora-Da-Hora#12]
### Descrição:
Método para se obter respostas iniciais sobre os requisitos através de um modelo funcional do produto esperado, antes de efetivamente construí-lo.

### Tarefas

- [x] Criar protótipo de baixa fidelidade(papel).
- [x] Realizar teste de usabilidade e navegabilidade.
- [x] Definir identidade visual.
- [x] Criar protótipo de alta fidelidade.

### Comentários

**Exemplos:**
https://github.com/2018-2-Desenho/CabecaVoleiJoelhoPe/wiki/Prot%C3%B3tipo
https://github.com/QueroMais/QueroMaisConversa/wiki/Prototyping

**Comment by jpcirqueira** [comment]
Foi feito o protótipo de baixa fidelidade, foram modeladas 8 telas, assim tivemos um melhor entendimento do projeto. Foi levado a professora, à parti de seu feedback surgiram alguns levantamentos relevantes para o projeto.

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-prototipacao
