### ISSUE TITLE
[DOC] Documento de Abertura do Projeto

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-Hora-Da-Hora#13]
### Descrição:
O documento tem como objetivo informar os propósitos, objetivos e requisitos de alto nível, além de especificações de planejamento do projeto.

### Tópicos do documento

- [x] EAP
- [x] Canvas 
- [x] Descrição do Projeto
- [x] Proposito 
- [x] Justificativa
- [x] Objetivos
- [x] Requisitos de alto nível
- [x] Riscos
- [x] Estimativa de custos
- [x] Partes interessadas
- [x] Requisitos para aprovação
- [x] Referencias bibliográficas 
- [x] Histórico de revisão 

### Comentários:
Nos tópicos de riscos e estimativa de custos será disponibilizado uma breve descrição e link para os planos que tratem do assunto.

**Comment by lukassxp** [comment]
Documento revisado e está ok!

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-tap
