### ISSUE TITLE
[TS02] Configurar Github Pages

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-Hora-Da-Hora#14]
### Descrição:
Github pages será a pagina de apresentação do produto e dos documentos relacionados a ele.

### Tarefas

- [x] Definir tecnologia a ser utilizada
- [x] Configurar ambiente
- [x] Criar tutorial de utilização

**Comment by caiooliv** [comment]
O ambiente do git pages está configurado para que os membros possam fazer o upload dos docs.
