### ISSUE TITLE
[TS03] Configurar Ambientes

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-Hora-Da-Hora#15]
### Descrição:
A configuração do ambiente busca impactar positivamente a produtividade da equipe de desenvolvimento.

### Tarefas

- [x] Docker
- [x] Integração contínua
- [x] Deploy contínuo

**Comment by matheus-rn** [comment]
O ambiente do frontend foi configurado, o travis é usado para q integração e deploy contínuo. O deploy da imagem está sendo feita no Docker Hub.
