### ISSUE TITLE
[DOC] Plano de Gestão e Configuração de Software

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-Hora-Da-Hora#17]
### Descrição:
<p align="justify">Responsável por definir as ferramentas que são utilizadas durante o desenvolvimento do software, descrevendo as iterações entre elas. Também serão abordados os procedimentos de gerência e configuração de software a ser seguidos no projeto.</p>

### Tópicos do documento

- [x] Sumário
- [x] Introdução
- [x] Ferramentas
- [x] Integração entre as ferramentas
- [x] Politicas
- [x] Uso de issues
- [x] Referências 
- [x] Histórico de revisão

**Comment by LucasSiqz** [comment]
Documento revisado, está de acordo com o planejado.

**Comment by lukassxp** [comment]
Ok! A parte do documento que trata sobre as ferramentas foi escrita de forma sucinta pois o documento de arquitetura deve descrever mais afundo essas questões.

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/plano-gcs
