### ISSUE TITLE
[DOC] Plano de Gerenciamento de Custos

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-Hora-Da-Hora#20]
### Descrição:
Visa realizar uma estimativa dos custos gerais do projeto. Para esta estimativa serão tomadas em consideração diversas variáveis contidas no projeto, dentre estas, o tempo de desenvolvimento, a quantidade de horas estimadas de dedicação ao projeto por parte dos desenvolvedores, os custos de equipamento dos desenvolvedores e demais gastos.

### Tópicos do documento

- [x] Introdução
- [x] Estimativa de custo
- [x] Custo de aquisição
- [x] Custo de pessoal
- [x] Custo de ferramentas
- [x] Custo de capacitação
- [x] Custo total
- [x] Referências
- [x] Histórico de revisão

### Comentários
**Exemplos:**
- https://botlino.github.io/docs/doc-tap

**Comment by lukassxp** [comment]
Documento foi feito e está aguardando revisão, durante o desenvolvimento do documento também se constatou a necessidade de um tópico para custos de capacitação tendo em vista que foram gastos recursos para tal fim.

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/plano-custos
