### ISSUE TITLE
[DOC] Plano de Gerenciamento de Riscos

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-Hora-Da-Hora#21]
### Descrição:
Consiste da identificação, análise, planejamento de respostas e controle dos riscos

### Tópicos do documento

- [x] Sumário
- [x] Introdução
- [x] Estrutura Analítica de Riscos
- [x] Análise quantitativa de riscos
- [x] Riscos levantados
- [x] Referências bibliográficas
- [x] Histórico de revisão

**Comment by LucasSiqz** [comment]
Foram levantados 13 riscos junto com sua probabilidade, impacto e ações a serem tomadas.

**Comment by matheus-rn** [comment]
Documento revisado e aprovado.

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/plano-riscos
