### ISSUE TITLE
[TRAINNING] Dojo de Pytest

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-Hora-Da-Hora#26]
### O que será estudado:
Será estudado a realização de teste unitários em python utilizando o pytest.

### Objetivo:
Capacitar os membros da equipe de desenvolvimento para fazer testes unitários em python.

**Estimativa de Duração** : 1:30 horas

**Comment by lukassxp** [comment]
| Tema:              |Teste unitários e testes com mock utilizando pytest   |
|----------------    |--------------------|
|**Data:**     | 06/03/2019      |
| **Instrutores:**       | Lucas M.(@lukassxp)      |
| **Nomes**              |**Presentes** |
| João Pedro(@jpcirqueira)          |          :heavy_check_mark:           |
| Matheus Cristo(@MatheusEstanislau)      |          :heavy_check_mark:           |
| Moacir(@MoacirMSJ)                          |          :heavy_check_mark:           |
| Renan(@RCristyan)                        |          :heavy_check_mark:           |
| Lucas Alexandre(@lucasA27)       | :heavy_check_mark:  |

**Obs:** Foi disponibilizado para os membros de MDS um arquivo com exemplos de testes, para que possam tirar duvidas e se basear futuramente. Os membros de MDS não desenvolveram código durante o Dojo apenas viram demonstrações feitas por mim e tiveram liberdade para tirar suas dúvidas.

**Aguardando feedback dos membros de MDS e aprovação dos membros de EPS para fechar a issue.**

**Comment by jpcirqueira** [comment]
me deu conhecimento básico de testes, irá ajudar durante no desenvolvimento do projeto.

**Comment by lucasA27** [comment]
Dojo muito bem explicado, que me deu noção básica sobre Pytest.

**Comment by RCristyan** [comment]
Antes não conhecia nada sobre testes, mas agora com esse Dojo tenho uma noção muito boa, que com certeza será útil no futuro do projeto

**Comment by MatheusEstanislau** [comment]
Forneceu uma excelente base para a utilização de testes unitários e testes com mocks para utilização no projeto.

**Comment by MoacirMSJ** [comment]
O Dojo de testes  me proporcionou uma visão básica sobre o Pytest e como proceder em alguns teste específicos.

**Comment by lukassxp** [comment]
Conforme feedback do grupo de MDS atividade atingiu seu objetivo e a issue pode ser considerada fechada.
