### ISSUE TITLE
[DOC] Folha de Estilo

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-Hora-Da-Hora#27]
### Descrição:
Estabelecer a folha de estilo usada no projeto.

### Tópicos do documento

- [x] Layout de código.
- [x] Estruturas de comentários.
- [x] Organização de estruturas de controle.
- [x] Indentação de estruturas de controle.
- [x] Rotinas
- [x] Convenção de nomeação.
- [x] Referências
- [x] Histórico de revisão.
 
### Comentários
Deve descrever as folhas de estilo das linguagens python e javascript.
[Link de execmplo](https://github.com/fga-eps-mds/2017.2-QueroCultura/wiki/Folha-de-estilo)

**Comment by MatheusEstanislau** [comment]
Criado documento Folha de Estilo com os guias de boas práticas do Python e React.

**Comment by RCristyan** [comment]
Documento da Folha de Estilo finalizado, visando organizar os códigos que serão implementados pela equipe

**Comment by LucasSiqz** [comment]
Documento revisado e aprovado!

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-folhaEstilo
