### ISSUE TITLE
[DOC] Documento de Arquitetura

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-Hora-Da-Hora#28]
### Descrição:
Estabelece os critérios de aceitação e atividades para o documento de arquitetura.

### Tópicos do documento
Lista de tópicos para serem realizadas. 

- [x] Introdução
- [x] Representação da arquitetura.
- [x] Metas e restrições de arquitetura.
- [x] Visão das história de usuário.
- [x] Visão lógica
- [x] Visão de implantação
- [x] Visão de implementação.
- [x] Tamanho e desempenho.
- [x] Qualidade
- [x] Referência
- [x] Histórico de revisão.

### Comentários
Exemplos: 
[Link de exemplo 1](https://github.com/fga-eps-mds/2017.2-QueroCultura/wiki/Documento-de-Arquitetura)
[Link de exemplo 2](https://github.com/2018-2-Desenho/CabecaVoleiJoelhoPe/wiki/Documento-de-Arquitetura)

**Comment by jpcirqueira** [comment]
documento esta aguardando revisão.

**Comment by lukassxp** [comment]
Documento revisado e por enquanto está ok! Caso seja necessário refatoração em função de alterações na arquitetura ou nos requisitos do produto será informado para que seja realizada ao longo das próximas sprints.

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-arquitetura
