### ISSUE TITLE
[DOC] Descrição de Metodologia 

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-Hora-Da-Hora#29]
### Descrição:
Estabelece os critérios de aceitação e atividades para o documento de descrição de metodologia. 

### Tópicos do documento
Lista de tópicos para serem realizadas. 

- [x] Introdução
- [x] Scrum
- [x] XP
- [x] Kanban
- [x] Referencia
- [x] Histórico de revisão

 
### Comentários
**Exemplos:**
https://github.com/2018-2-Desenho/CabecaVoleiJoelhoPe/wiki/Descri%C3%A7%C3%A3o-da-metodologia
https://fga-eps-mds.github.io/2018.2-Integra-Vendas/docs/plano-metodologico

**Comment by LucasSiqz** [comment]
Foi feita a descrição da metodologia levando em consideração os recursos que serão utilizados de cada metodologia, além das descritas na issue foi adicionado o RUP, pois foi utilizado conceitos de sua fase inicial para o levantamento de requisitos.

**Comment by lukassxp** [comment]
Documento revisado, existe apenas uma observação um dos títulos de seção está todo em letra maiúscula enquanto os demais estão apenas iniciando com letras maiúscula, após realizar essa pequena correção o doc está ok!

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-descricao-metodologia
