### ISSUE TITLE
Dojo de docker

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-Hora-Da-Hora#3]
### O que será estudado:
O que é o docker, Imagens, containers e como será aplicado ao projeto.

### Objetivo:
Introduzir para a equipe de MDS o que é o docker, porque e como será utilizado por eles.

**Estimativa de Duração** : 1 hora.

**Comment by matheus-rn** [comment]
| Tema:          	|Docker | 
|----------------	|--------------------|
|**Data:** 	| 19/03/2019|
| **Instrutores:**   	| Matheus Rodrigues |
| **Descrição:**     	| Imagens, containers e como será aplicado ao projeto| 
| **Nomes**          	| **Presentes** | 
| João Pedro     	|          ✔         | 
| Matheus Cristo 	|          ✔         | 
| Moacir         	            |          ✔         | 
| Renan       	            |          ✔         |
| Lucas Alexandre       |          ✔         |
