### ISSUE TITLE
[REFACTOR] Protótipo de Alta Fidelidade.

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-Hora-Da-Hora#30]
### Motivo de refatoração:
Refatoração deve ser feita pois não atingiu qualidade necessária para ser considerado um protótipo de alta fidelidade.

### Tópicos de aceitação:
- [x] Teste de usabilidade.
- [x] Restilização.
- [x] Emblemas e logos.
 

### Comentários:
[Link de exemplo](https://fga-eps-mds.github.io/2018.2-CarDefense/docs/usabilidade.html)

**Comment by caiooliv** [comment]
Documento revisado, com todos os critérios de aceitação ok's.

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-prototipacao
