### ISSUE TITLE
[TS04] Configurar Ambiente de Desenvolvimento do Back-end 

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-Hora-Da-Hora#31]
### Descrição:
A configuração do ambiente busca impactar positivamente a produtividade da equipe de desenvolvimento.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Docker
- [x] Integração contínua.
- [x] Deploy contínuo da imagem no docker hub.

**Comment by matheus-rn** [comment]
O ambiente da api gateway foi configurada, a integração contínua e o deploy da imagem no Docker Hub é mediada pelo Travis CI.
