### ISSUE TITLE
Estudo básico de react js

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-Hora-Da-Hora#5]
### O que será estudado:

1. O que é ReactJS
2. Criar um projeto.
3. O que são componentes.
4. Utilizar dados de uma API.
5. Navegação.

### Objetivo:
Aprender os conceitos básicos de react js que será utilizado no projeto na pratica, para isso foi disponibilizado um curso gratuito na plataforma rocketseat disponível em: https://station.rocketseat.com.br/, sendo assim os membros da equipe de MDS tem como objetivo finalizar esse curso.

**Estimativa de Duração** : 2 horas.

**Comment by jpcirqueira** [comment]
Foi importante para introdução a ferramenta ReactJS, assim deixar claro como funciona a estrutura principal da ferramenta e como deve ser manipulada. Após o término do curso tive uma melhor abstração sobre a ferramenta.

**Comment by lucasA27** [comment]
Foi fundamental o estudo básico de Reactjs, para maior entedimento de como será usada durante o trabalho.

**Comment by MatheusEstanislau** [comment]
Introdução essencial para utilização do ReactJS,  pois ensina a estruturação básica de um projeto e como utilizar dados de uma API.

**Comment by MoacirMSJ** [comment]
Foi importante para ter um conhecimento básico sobre a  ferramenta.
