### ISSUE TITLE
[TS01] Configurar Slack

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-Hora-Da-Hora#7]
### Descrição:
Configurar canais e bots para o uso do slack.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Convidar membros 
- [x] Criar canais
- [x] Configurar bot da daily
- [x] Configurar bot do github

 
### Comentários
O uso do slack é necessário para que exista uma boa comunicação do grupo, por isso deve ser configurado antes de começar o uso.

**Comment by caiooliv** [comment]
Foi configurado todos os bots e canais necessários para que a equipe possa usar o slack como principal ferramenta de comunicação.

**Comment by lukassxp** [comment]
Todos os membros entraram no Workspace e o funcionamento dos bots foi testado e aprovado.
