### ISSUE TITLE
[DOC] Observação

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-Hora-Da-Hora#8]
### Descrição:
Observação participativa de outros aplicativos para elicitar requisitos.

### Tópicos do documento
Lista de tópicos para serem realizadas. 

- [x] Sumário.
- [x] Introdução.
- [x] Observação.
- [x] Conclusão.
- [x] Referencias bibliográficas.
- [x] Histórico de revisão.

**Comment by MoacirMSJ** [comment]
Foi feito o documento de Observação utilizando os seguintes aplicativos Monitoria+App e Monitoria USJT disponível em: https://fga-eps-mds.github.io/2019.1-Hora-Da-Hora/docs/Observa%C3%A7%C3%A3o

**Comment by lukassxp** [comment]
Documento revisado o conteúdo está ok, mas necessita de refatoração no layout do documento para se adequar ao template do grupo. Após a as correções indicadas a issue pode ser fechada.

**Comment by MoacirMSJ** [comment]
Feita a refatoração do documento de Observação.

**Comment by RCristyan** [comment]
Documentação concluída e formatada em Markdown

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-observacao
