### ISSUE TITLE
[DOC] Documento de Visão

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-Hora-Da-Hora#9]
### Descrição:
O documento de visão é o responsável por demonstrar a visão geral, as características e os objetivos do produto a ser produzido. Este documento também fornece uma visão unificada das expectativas do cliente em relação ao software, e ajuda a reduzir riscos.

### Tópicos do documento

- [x] Introdução
- [x] Descrição de usuário
- [x] Envolvidos
- [x] Visão geral do produto
- [x] Recursos do produto
- [x] Requisitos não funcionais
- [x] Referencias bibliográficas
- [x] Histórico de revisão

### Comentários
Os requisitos não funcionais devem ser detalhados utilizando NFR framework.

**Exemplos de documentos:** 

- https://github.com/fga-eps-mds/2017.2-QueroCultura/wiki/Documento-de-Vis%C3%A3o
- https://botlino.github.io/docs/doc-visao

**Comment by LucasSiqz** [comment]
Documento revisado e está conforme o planejado, porém o tópico dos envolvidos no projeto deve ser refatorado para que seja descrita de forma menos genérica os papéis dos membros da equipe de EPS. Após a as correções indicadas a issue pode ser fechada.

**Comment by lucasA27** [comment]
Foi feito a alteração no documento de visão sobre o tópico dos envolvidos, relacionado aos papéis dos membros da equipe de EPS.

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-visao
